# Filter by hash
similarity_threshold: 0.03
hash_size: 8

# Filter by order
step: 3

# Image set split
image_groups: 7

# Camera params (ZED):
fx: 1064.27
fy: 1064.27
cx: 986.697
cy: 559.228
k1: 0
k2: 0
p1: 0
p2: 0
k3: 0
k4: 0
k5: 0
k6: 0

# Stereo matching:
num_iterations: 3
geom_consistency: 0
filter: 1
max_image_size: 1000
window_step: 2
window_radius: 3
num_samples: 10

# Colmap visualization:
initial_check_interval: 5
refresh_interval: 3
flip_orientation: true
frustum: true

# Sparse outlier removal:
s_nb_neighbors: 20
s_std_ratio: 2.0

# Dense outlier removal:
d_nb_neighbors: 50
d_std_ratio: 0.0001
